/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LoginImport } from './routes/login'
import { Route as AuthenticatedImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexImport } from './routes/_authenticated/index'
import { Route as AuthenticatedReportsIndexImport } from './routes/_authenticated/reports/index'
import { Route as AuthenticatedOwnersIndexImport } from './routes/_authenticated/owners/index'
import { Route as AuthenticatedManagementIndexImport } from './routes/_authenticated/management/index'
import { Route as AuthenticatedFlightsIndexImport } from './routes/_authenticated/flights/index'
import { Route as AuthenticatedClientsIndexImport } from './routes/_authenticated/clients/index'
import { Route as AuthenticatedAircraftIndexImport } from './routes/_authenticated/aircraft/index'
import { Route as AuthenticatedFlightsFlightIdImport } from './routes/_authenticated/flights/$flightId'
import { Route as AuthenticatedAircraftAircraftIdImport } from './routes/_authenticated/aircraft/$aircraftId'

// Create Virtual Routes

// Create/Update Routes

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedRoute = AuthenticatedImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedIndexRoute = AuthenticatedIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedReportsIndexRoute = AuthenticatedReportsIndexImport.update({
  id: '/reports/',
  path: '/reports/',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedOwnersIndexRoute = AuthenticatedOwnersIndexImport.update({
  id: '/owners/',
  path: '/owners/',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedManagementIndexRoute = AuthenticatedManagementIndexImport.update({
  id: '/management/',
  path: '/management/',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedFlightsIndexRoute = AuthenticatedFlightsIndexImport.update({
  id: '/flights/',
  path: '/flights/',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedClientsIndexRoute = AuthenticatedClientsIndexImport.update({
  id: '/clients/',
  path: '/clients/',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedAircraftIndexRoute = AuthenticatedAircraftIndexImport.update({
  id: '/aircraft/',
  path: '/aircraft/',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedFlightsFlightIdRoute = AuthenticatedFlightsFlightIdImport.update({
  id: '/flights/$flightId',
  path: '/flights/$flightId',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedAircraftAircraftIdRoute = AuthenticatedAircraftAircraftIdImport.update({
  id: '/aircraft/$aircraftId',
  path: '/aircraft/$aircraftId',
  getParentRoute: () => AuthenticatedRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/aircraft/$aircraftId': {
      id: '/_authenticated/aircraft/$aircraftId'
      path: '/aircraft/$aircraftId'
      fullPath: '/aircraft/$aircraftId'
      preLoaderRoute: typeof AuthenticatedAircraftAircraftIdImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/flights/$flightId': {
      id: '/_authenticated/flights/$flightId'
      path: '/flights/$flightId'
      fullPath: '/flights/$flightId'
      preLoaderRoute: typeof AuthenticatedFlightsFlightIdImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/aircraft/': {
      id: '/_authenticated/aircraft/'
      path: '/aircraft'
      fullPath: '/aircraft'
      preLoaderRoute: typeof AuthenticatedAircraftIndexImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/clients/': {
      id: '/_authenticated/clients/'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof AuthenticatedClientsIndexImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/flights/': {
      id: '/_authenticated/flights/'
      path: '/flights'
      fullPath: '/flights'
      preLoaderRoute: typeof AuthenticatedFlightsIndexImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/management/': {
      id: '/_authenticated/management/'
      path: '/management'
      fullPath: '/management'
      preLoaderRoute: typeof AuthenticatedManagementIndexImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/owners/': {
      id: '/_authenticated/owners/'
      path: '/owners'
      fullPath: '/owners'
      preLoaderRoute: typeof AuthenticatedOwnersIndexImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/reports/': {
      id: '/_authenticated/reports/'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsIndexImport
      parentRoute: typeof AuthenticatedImport
    }
  }
}

// Create and export the route tree

interface AuthenticatedRouteChildren {
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedAircraftAircraftIdRoute: typeof AuthenticatedAircraftAircraftIdRoute
  AuthenticatedFlightsFlightIdRoute: typeof AuthenticatedFlightsFlightIdRoute
  AuthenticatedAircraftIndexRoute: typeof AuthenticatedAircraftIndexRoute
  AuthenticatedClientsIndexRoute: typeof AuthenticatedClientsIndexRoute
  AuthenticatedFlightsIndexRoute: typeof AuthenticatedFlightsIndexRoute
  AuthenticatedManagementIndexRoute: typeof AuthenticatedManagementIndexRoute
  AuthenticatedOwnersIndexRoute: typeof AuthenticatedOwnersIndexRoute
  AuthenticatedReportsIndexRoute: typeof AuthenticatedReportsIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedAircraftAircraftIdRoute: AuthenticatedAircraftAircraftIdRoute,
  AuthenticatedFlightsFlightIdRoute: AuthenticatedFlightsFlightIdRoute,
  AuthenticatedAircraftIndexRoute: AuthenticatedAircraftIndexRoute,
  AuthenticatedClientsIndexRoute: AuthenticatedClientsIndexRoute,
  AuthenticatedFlightsIndexRoute: AuthenticatedFlightsIndexRoute,
  AuthenticatedManagementIndexRoute: AuthenticatedManagementIndexRoute,
  AuthenticatedOwnersIndexRoute: AuthenticatedOwnersIndexRoute,
  AuthenticatedReportsIndexRoute: AuthenticatedReportsIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

export interface FileRoutesByFullPath {
  '': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/': typeof AuthenticatedIndexRoute
  '/aircraft/$aircraftId': typeof AuthenticatedAircraftAircraftIdRoute
  '/flights/$flightId': typeof AuthenticatedFlightsFlightIdRoute
  '/aircraft': typeof AuthenticatedAircraftIndexRoute
  '/clients': typeof AuthenticatedClientsIndexRoute
  '/flights': typeof AuthenticatedFlightsIndexRoute
  '/management': typeof AuthenticatedManagementIndexRoute
  '/owners': typeof AuthenticatedOwnersIndexRoute
  '/reports': typeof AuthenticatedReportsIndexRoute
}

export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/': typeof AuthenticatedIndexRoute
  '/aircraft/$aircraftId': typeof AuthenticatedAircraftAircraftIdRoute
  '/flights/$flightId': typeof AuthenticatedFlightsFlightIdRoute
  '/aircraft': typeof AuthenticatedAircraftIndexRoute
  '/clients': typeof AuthenticatedClientsIndexRoute
  '/flights': typeof AuthenticatedFlightsIndexRoute
  '/management': typeof AuthenticatedManagementIndexRoute
  '/owners': typeof AuthenticatedOwnersIndexRoute
  '/reports': typeof AuthenticatedReportsIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/aircraft/$aircraftId': typeof AuthenticatedAircraftAircraftIdRoute
  '/_authenticated/flights/$flightId': typeof AuthenticatedFlightsFlightIdRoute
  '/_authenticated/aircraft/': typeof AuthenticatedAircraftIndexRoute
  '/_authenticated/clients/': typeof AuthenticatedClientsIndexRoute
  '/_authenticated/flights/': typeof AuthenticatedFlightsIndexRoute
  '/_authenticated/management/': typeof AuthenticatedManagementIndexRoute
  '/_authenticated/owners/': typeof AuthenticatedOwnersIndexRoute
  '/_authenticated/reports/': typeof AuthenticatedReportsIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/login'
    | '/'
    | '/aircraft/$aircraftId'
    | '/flights/$flightId'
    | '/aircraft'
    | '/clients'
    | '/flights'
    | '/management'
    | '/owners'
    | '/reports'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/'
    | '/aircraft/$aircraftId'
    | '/flights/$flightId'
    | '/aircraft'
    | '/clients'
    | '/flights'
    | '/management'
    | '/owners'
    | '/reports'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/'
    | '/_authenticated/aircraft/$aircraftId'
    | '/_authenticated/flights/$flightId'
    | '/_authenticated/aircraft/'
    | '/_authenticated/clients/'
    | '/_authenticated/flights/'
    | '/_authenticated/management/'
    | '/_authenticated/owners/'
    | '/_authenticated/reports/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
